import { IconProp } from '@fortawesome/fontawesome-svg-core';
import {
	faBell,
	faBookmark,
	faCalendar,
	faComment,
	faComments,
	faCopy,
	faEye,
	faFaceSmile,
	faFlag,
	faHeart,
	faPaperPlane,
	faUser,
} from '@fortawesome/free-regular-svg-icons';
import {
	faHeart as faHeartSolid,
	faShare,
	faBookmark as faBookmarkSolid,
	faGear,
	faEllipsisV,
	faListDots,
	faThumbTack,
	faUserPlus,
	faUserCheck,
	faHouse as faHouseSolid,
	faSearch,
	faBell as faBellSolid,
	faComments as faCommentsSolid,
	faBullhorn,
	faGlobe,
	faUnlock,
	faLock,
	faAt,
	faImages,
	faBellSlash,
	faCommentSlash,
	faBan,
	faTriangleExclamation,
	faLink,
	faArrowUpFromBracket,
	faPen,
	faTrash,
	faIdCard,
	faBarsStaggered,
	faUsers,
	faUserCog,
	faShieldAlt,
	faPaintBrush,
	faUserShield,
	faHashtag,
	faPanorama,
	faUpload,
	faClipboardUser,
	faTimeline,
	faHouseChimney,
	faCamera,
	faQuoteRight,
	faUser as solidUser,
	faInfo,
	faReply,
	faGears,
	faCheck,
} from '@fortawesome/free-solid-svg-icons';

export const AppIcons = {
	heartSolid: faHeartSolid as IconProp,
	heartRegular: faHeart as IconProp,
	comment: faComment as IconProp,
	share: faShare as IconProp,
	bookmarkRegular: faBookmark as IconProp,
	bookmarkSolid: faBookmarkSolid as IconProp,
	setting: faGear,
	menu: faEllipsisV,
	list: faListDots,
	pin: faThumbTack,
	follow: faUserPlus,
	followed: faUserCheck,
	homeRegular: faHouseSolid,
	homeSolid: faHouseChimney,
	search: faSearch,
	notiRegular: faBell,
	notiSolid: faBellSolid,
	conversationRegular: faComments,
	conversationSolid: faCommentsSolid,
	announcement: faBullhorn,
	globe: faGlobe,
	unlock: faUnlock,
	lock: faLock,
	mention: faAt,
	images: faImages,
	emoji: faFaceSmile,
	poll: faListDots,
	schedule: faCalendar,
	noNotification: faBellSlash,
	noMessage: faCommentSlash,
	sendMessage: faPaperPlane,
	mute: faBellSlash,
	block: faBan,
	report: faTriangleExclamation,
	copyLink: faLink,
	externalShare: faArrowUpFromBracket,
	edit: faPen,
	delete: faTrash,
	userMetadata: faIdCard,
	timeline: faBarsStaggered,
	users: faUsers,
	user: faUser,
	addUser: faUserPlus,
	privacy: faShieldAlt,
	personalization: faPaintBrush,
	accountManagement: faUserCog,
	profileSettings: faUserShield,
	hashtag: faHashtag,
	camera: faCamera,
	coverPhoto: faPanorama,
	upload: faUpload,
	preview: faEye,
	shareUser: faClipboardUser,
	quote: faQuoteRight,
	avatar: solidUser,
	info: faInfo,
	reply: faReply,
	flag: faFlag,
	developing: faGears,
	copy: faCopy as IconProp,
	check: faCheck as IconProp,
};
