default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    setup_ci
    
    # Update match (optional, if you use match for code signing)
    # match(type: "appstore", readonly: is_ci)

    increment_build_number(xcodeproj: "FindOutMedia.xcodeproj")
    
    build_app(
      scheme: "FindOutMedia",
      workspace: "FindOutMedia.xcworkspace",
      clean: true
    )
    
    upload_to_app_store(
      force: true,
      skip_screenshots: true,
      skip_metadata: true,
      skip_waiting_for_build_processing: true
    )
  end
end
