default_platform(:android)

platform :android do
  desc "Deploy a new version to the Google Play"
  lane :release do
    # Check if the keystore variables are set
    unless ENV["ANDROID_KEYSTORE_PASSWORD"] && ENV["ANDROID_KEY_ALIAS"] && ENV["ANDROID_KEY_PASSWORD"]
      UI.user_error!("Example: ANDROID_KEYSTORE_PASSWORD, ANDROID_KEY_ALIAS, ANDROID_KEY_PASSWORD")
    end

    gradle(
      task: "bundleRelease",
      properties: {
        "ANDROID_KEYSTORE_FILE" => ENV["ANDROID_KEYSTORE_FILE"],
        "ANDROID_KEYSTORE_PASSWORD" => ENV["ANDROID_KEYSTORE_PASSWORD"],
        "ANDROID_KEY_ALIAS" => ENV["ANDROID_KEY_ALIAS"],
        "ANDROID_KEY_PASSWORD" => ENV["ANDROID_KEY_PASSWORD"],
      }
    )

    upload_to_play_store(
      track: 'internal',
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end
end
